services:
  mysql-db:
    image: mysql:8.3.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ProductsDataBase
    ports:
      - "3306:3306"
    volumes:
      - "D:/Micro Services Course/Mine/DataBase/MySql/sql1.sql:/docker-entrypoint-initdb.d/sql1.sql"
    networks:
      - Ecommerce-network


  product-api:
    image: heshamayman0/productimage:v1.2
    container_name: product-api
    depends_on:
      - mysql-db
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PASSWORD=admin
      - PortNumber=3306
      - MYSQL_DATABASE=ProductsDataBase
    ports:
      - "8080:8080"
    networks:
      - Ecommerce-network


  postgres-db:
    image: postgres:18
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: UserMangement
    ports:
      - "5435:5432"
    volumes:
      - "D:/Micro Services Course/Mine/DataBase/postgress/sql2.sql:/docker-entrypoint-initdb.d/sql2.sql"
    networks:
      - Ecommerce-network


  user-api:
    image: heshamayman0/userimage:V1.2
    container_name: user-api
    depends_on:
      - postgres-db
    environment:
      - MyPostGrHost=postgres-db
      - MyPostGrPassword=admin
      - MyPostGrPort=5432
      - MyPostGrDatabase=UserMangement
    ports:
      - "9090:9090"
    networks:
      - Ecommerce-network


  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongo-db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - "D:/Micro Services Course/Mine/DataBase/mongo:/docker-entrypoint-initdb.d"
    networks:
      - Ecommerce-network

  orders-api:
    image: heshamayman0/orderimage:V1.2
    container_name: orders
    depends_on:
      - mongodb
      - user-api
      - product-api
    environment:
      - MONGODB_HOST=mongo-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=OrderMangement
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=adminpassword
      - UserMicroServiceName=user-api
      - UserMicroServicePort=9090
      - ProductsMicroServiceName=product-api
      - ProductsMicroServicePort=8080
    ports:
      - "5043:8080"
    networks:
      - Ecommerce-network

networks:
  Ecommerce-network:
    driver: bridge